### ISSUE TITLE
Detailed readme request

### ISSUE THREAD

**Issue by Rheinmetallskorpion** [wis/mpvSockets#2]
Thanks for making this useful tool. However, as a new mpv user, I have no idea about the way it should be used. Googling doesn't help much either. For the sake of the upcoming new users like me, would you specify how to make this useful in the readme file? Thanks.

**Comment by wis** [comment]
fixed in be9b7ca84456466e54331bab59441ac207659c1c, let me know if you need anything else.
remember to click the ⭐ (star) button, as it means something to me.

**Comment by Gooberpatrol66** [comment]
What do you do after you install the lua script, so that each mpv uses the right input-ipc-server?

**Comment by wis** [comment]
after you install the script when an mpv instance is created/launched it creates its own IPC server and socket at `/tmp/mpvSockets/` the filename of the socket is the process id (PID) of that mpv instance. @Gooberpatrol66
