### ISSUE TITLE
Doesn't run due to error: attempt to call method 'getpid' (a nil value)

### ISSUE THREAD

**Issue by Flurrywinde** [wis/mpvSockets#3]
After putting mpvSockets.lua in my mpv scripts directory, running mpv gives the following error (and the socket not created):
```
$ mpv ~/Downloads/*.mp4
[mpvSockets]
[mpvSockets] stack traceback:
[mpvSockets]    /home/kanon/.config/mpv/scripts/mpvSockets.lua:29: in main chunk
[mpvSockets]    [C]: in ?
[mpvSockets]    [C]: in ?
[mpvSockets] Lua error: /home/kanon/.config/mpv/scripts/mpvSockets.lua:29: attempt to call method 'getpid' (a nil value)
```
`mpv --version` gives:
```
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
```

**Comment by wis** [comment]
Hi, I have no idea why utils would be nil or not imported correctly
``` .lua
local utils = require 'mp.utils'
...
...
ppid = utils.getpid()
```
maybe we can ask one of the developers of mpv

**Comment by Flurrywinde** [comment]
I just tried it again, and it works. In the interim, I reinstalled my OS from scratch. I suspect the problem before was due to a seriously messed up installation of Ubuntu which had many other very strange problems, not just this, but now I'm on Arch. So I suspect this was just my weird problem, but there doesn't seem any way to test it further. Sorry for the noise, if that's indeed what the problem was!

FWIW, here's my mpv and kernel version:
```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.1
```
`uname -r` = `5.10.16-1-lts`

**Comment by wis** [comment]
no worries, thank you for reporting it.
[i use arch btw](https://www.google.com/search?q=I+use+arch+btw) too :smile:.
I still have no idea why that error happened though, an mpv developer would know better, I might show them this issue and ask them.
