### ISSUE TITLE
Script explanation

### ISSUE THREAD

**Issue by aplaikner** [wis/mpvSockets#4]
Hello, could you explain really short what this script does? I've read the README and it says something about creating a new socket for each mpv instance. But why would you create a socket for playing videos and why is it so important to create a new one for each instance?

**Comment by wis** [comment]
Hi,
> could you explain really short what this script does? 

what this script does is only add an argument (`input-ipc-server`) as if you launched mpv with that argument like `mpv --input-ipc-server <path_to_socket>`, the path is `/tmp/mpvSockets/`+`<the process ID of the just started instance of mpv the script is running in>` this path is where the socket will be created.

> But why would you create a socket for playing videos

sockets are used to communicate between programs, Unix sockets are just like files and have paths, Windows sockets have names and are not files, you can use this socket to control an mpv instance by sending it [commands](https://mpv.io/manual/stable/#id7) and control it from other scripts, for example bash scripts.

>why is it so important to create a new one for each instance

so you can control each instance (in case you're watching multiple videos at the same time) separately.
